#!/usr/bin/env python3
"""Regenerate tests/ir_reference_citations.txt.

docs/IR_REFERENCE.md cites src/*.kr by line number, and line numbers rot: at
the last audit 146 of 153 citations pointed at unrelated code while still
being in range, which reads as valid and is the most insidious form of this
defect. This records a fingerprint of the line each citation points at, so
tests/run_tests.sh can tell you WHICH citations moved.

After editing src/ or the doc's citations:  python3 scripts/gen-ir-reference-citations.py
"""
import hashlib, re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
doc = os.path.join(ROOT, "docs/IR_REFERENCE.md")
out = os.path.join(ROOT, "tests/ir_reference_citations.txt")

s = open(doc).read()
cites = sorted(set(re.findall(r'src/([a-z_0-9]+\.kr):(\d+)', s)), key=lambda t: (t[0], int(t[1])))
cache = {}
rows, skipped = [], 0
for f, n in cites:
    if f not in cache:
        p = os.path.join(ROOT, "src", f)
        cache[f] = open(p).read().split("\n") if os.path.exists(p) else []
    lines = cache[f]
    i = int(n)
    if i - 1 >= len(lines):
        skipped += 1
        continue
    content = lines[i - 1].strip()
    if not content:
        skipped += 1
        continue
    h = hashlib.sha1(content.encode()).hexdigest()[:12]
    rows.append(f"src/{f}:{n} {h}")

with open(out, "w") as fh:
    fh.write("# Generated by scripts/gen-ir-reference-citations.py -- do not hand-edit.\n")
    fh.write("# <citation> <sha1-12 of the stripped source line it points at>\n")
    fh.write("\n".join(rows) + "\n")
print(f"wrote {len(rows)} citations to {out} ({skipped} skipped: blank or out of range)")
